name: ocr
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13.2
  - charset-normalizer
  - rich
  - numpy
  - typing-extensions
  - pydantic
  - opencv
  - setuptools
  - pytesseract
  - starlette
  - requests
  - packaging
  - wheel
  - pillow
  - certifi
  - openai
  - idna
  - matplotlib
  - uvicorn
  - tqdm
  - anyio
  - fastapi
  - pip
  - urllib3
  - pip:
      - black==25.9.0
      - brotli==1.2.0
      - brotlicffi==1.0.9.2
      - colorama==0.4.6
      - doclayout_yolo==0.0.4
      - easyocr==1.7.2
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.121.0
      - fastapi-cli==0.0.13
      - flake8==7.3.0
      - h2==4.3.0
      - httptools==0.7.1
      - imagesize==1.4.1
      - isort==7.0.0
      - munkres==1.1.4
      - mypy==1.18.2
      - openai==1.109.1
      - opencv-contrib-python==4.10.0.84
      - paddleocr==3.3.1
      - pip==25.2
      - pypdfium2==5.0.0
      - PySocks==1.7.1
      - pytesseract==0.3.13
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - tornado==6.5.2
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - wheel==0.45.1
      - zstandard==0.25.0
